### PR TITLE
#update_I change some shit

### PR DESCRIPTION
**Pull request by Nguyen177013**

### CODE REVIEW

**Comment by ItsaMeChun** [comment]
hi there
can you explain more about the Virtural

**Comment by ItsaMeChun** [comment]
why use ICollection instead of List

**Comment by Nguyen177013** [comment]
> hi there can you explain more about the Virtural

you use virtual to create a proxy around the entity modal and it also support lazy loading to increase the server performance

**Comment by Nguyen177013** [comment]
> why use ICollection instead of List

List is a data structure and it contain a lot of method and some of them we don't even use it.
On the other hand ICollections is a interface was highly supported for Entity framework, it also allow you to use method add/ update/ delete to interacted with the database

**Comment by ItsaMeChun** [comment]
kinda reasonable

**Pull request merged**
